### ISSUE TITLE
Remove blockcypher API

### ISSUE THREAD

**Issue by clemsos** [proofofexistence/proofofexistence#4]
- [x] add insight to services config (#6)
- [x] replace transactions links on detail page with insight links (#6)
- [x] change links in notification email
- [x] change payment script
- [x] drop blockcypher webhooks usage
- [x] change sweep script
- [x] replace blockcypher API calls with insight API (#7)
- [x] update tests (#7)
- [x] remove extra fixtures (#7)
- [x] update docs (config)
- [ ] switch default config to proofofexistence servers

**Comment by christopheradams** [comment]
Let's update the default configuration similar to this:

```yaml
services:
  blockcypher:
    url: https://api.blockcypher.com/v1
  insight:
    mainnet:
      url: https://insight.bitpay.com
      api: /api
    testnet:
      url: https://test-insight.bitpay.com
      api: /api
```

**Comment by clemsos** [comment]
fix by #7
